# Generated by Django 4.2.3 on 2023-10-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('sprincipal', models.CharField(max_length=50)),
                ('sfee', models.IntegerField()),
            ],
        ),
    ]
